namespace WeakMemory

/-!
# Weak-memory verification foundations

This file is the first formal milestone for the 14G research route. It keeps
three layers separate:

1. memory-order and execution-graph vocabulary;
2. the sequential specification of a stack;
3. the abstract successful-CAS commits of Treiber's stack.

The theorem `Treiber.commitTrace_linearizable` proves that every abstract
commit trace is a legal sequential stack history. A later milestone must prove
that every allowed release-acquire execution of the C algorithm induces such a
commit trace. We deliberately do not claim that bridge theorem yet.
-/

inductive MemoryOrder where
  | relaxed
  | acquire
  | release
  | acqRel
  | seqCst
  deriving Repr, DecidableEq

namespace MemoryOrder

/-- Whether an operation imports the view published by a release operation. -/
def hasAcquire : MemoryOrder → Bool
  | .acquire | .acqRel | .seqCst => true
  | .relaxed | .release => false

/-- Whether an operation publishes earlier writes to an acquiring operation. -/
def hasRelease : MemoryOrder → Bool
  | .release | .acqRel | .seqCst => true
  | .relaxed | .acquire => false

@[simp] theorem acquire_hasAcquire : hasAcquire .acquire = true := rfl
@[simp] theorem release_hasRelease : hasRelease .release = true := rfl
@[simp] theorem relaxed_hasNoAcquire : hasAcquire .relaxed = false := rfl
@[simp] theorem relaxed_hasNoRelease : hasRelease .relaxed = false := rfl

end MemoryOrder

inductive Action where
  | read
  | write
  | compareExchange
  deriving Repr, DecidableEq

/-- One shared-memory event. Locations and values are abstract natural IDs. -/
structure Event where
  id : Nat
  thread : Nat
  action : Action
  location : Nat
  value : Int
  order : MemoryOrder
  deriving Repr, DecidableEq

abbrev Relation (α : Type) := α → α → Prop

/--
A deliberately small execution-graph interface.

Well-formedness and the full RC11 consistency axioms will be added after the
algorithm-independent graph layer has stabilized.
-/
structure Execution where
  events : List Event
  programOrder : Relation Event
  readsFrom : Relation Event
  modificationOrder : Relation Event

namespace Execution

/-- A release event synchronizes with an acquire event that reads from it. -/
def synchronizesWith (execution : Execution) (source target : Event) : Prop :=
  execution.readsFrom source target ∧
    source.order.hasRelease = true ∧
    target.order.hasAcquire = true

/-- The transitive closure generated by program-order and synchronizes-with. -/
inductive HappensBefore (execution : Execution) : Relation Event where
  | programOrder {source target} :
      execution.programOrder source target →
      HappensBefore execution source target
  | synchronizesWith {source target} :
      execution.synchronizesWith source target →
      HappensBefore execution source target
  | transitive {first middle last} :
      HappensBefore execution first middle →
      HappensBefore execution middle last →
      HappensBefore execution first last

theorem releaseAcquireEdge_isHappensBefore (execution : Execution)
    {source target : Event}
    (readsFrom : execution.readsFrom source target)
    (sourceIsRelease : source.order.hasRelease = true)
    (targetIsAcquire : target.order.hasAcquire = true) :
    execution.HappensBefore source target := by
  apply HappensBefore.synchronizesWith
  exact ⟨readsFrom, sourceIsRelease, targetIsAcquire⟩

end Execution

namespace StackSpec

inductive Operation (α : Type) where
  | push : α → Operation α
  | pop : Operation α
  deriving Repr, DecidableEq

inductive Response (α : Type) where
  | pushed
  | popped : Option α → Response α
  deriving Repr, DecidableEq

structure CompletedOperation (α : Type) where
  operation : Operation α
  response : Response α
  deriving Repr, DecidableEq

/-- The ordinary sequential specification against which Treiber is checked. -/
def step : List α → Operation α → Response α × List α
  | stack, .push value => (.pushed, value :: stack)
  | [], .pop => (.popped none, [])
  | value :: rest, .pop => (.popped (some value), rest)

/-- A history is legal when every response agrees with the sequential spec. -/
inductive Legal :
    List α → List (CompletedOperation α) → List α → Prop where
  | nil (stack : List α) : Legal stack [] stack
  | cons {before after final : List α}
      (entry : CompletedOperation α)
      (rest : List (CompletedOperation α))
      (headIsLegal :
        step before entry.operation = (entry.response, after))
      (tailIsLegal : Legal after rest final) :
      Legal before (entry :: rest) final

end StackSpec

namespace Treiber

/--
The abstract atomic commits of Treiber's algorithm.

`popValue v` records a successful CAS that removed `v`; `popEmpty` records a
load that observed an empty head. Failed CAS attempts are deliberately absent:
they are internal steps and do not linearize a stack operation.
-/
inductive Commit (α : Type) where
  | push : α → Commit α
  | popValue : α → Commit α
  | popEmpty : Commit α
  deriving Repr, DecidableEq

namespace Commit

def completed : Commit α → StackSpec.CompletedOperation α
  | .push value =>
      { operation := .push value, response := .pushed }
  | .popValue value =>
      { operation := .pop, response := .popped (some value) }
  | .popEmpty =>
      { operation := .pop, response := .popped none }

end Commit

/-- The three possible state changes at a Treiber linearization point. -/
inductive CommitStep : List α → Commit α → List α → Prop where
  | push (value : α) (stack : List α) :
      CommitStep stack (.push value) (value :: stack)
  | popValue (value : α) (rest : List α) :
      CommitStep (value :: rest) (.popValue value) rest
  | popEmpty :
      CommitStep ([] : List α) .popEmpty []

theorem commitStep_matchesSpec {before after : List α} {commit : Commit α}
    (step : CommitStep before commit after) :
    StackSpec.step before commit.completed.operation =
      (commit.completed.response, after) := by
  cases step <;> rfl

/-- A sequence of successful linearization-point commits. -/
inductive CommitTrace : List α → List (Commit α) → List α → Prop where
  | nil (stack : List α) : CommitTrace stack [] stack
  | cons {before middle final : List α}
      (commit : Commit α)
      (rest : List (Commit α))
      (headStep : CommitStep before commit middle)
      (tailTrace : CommitTrace middle rest final) :
      CommitTrace before (commit :: rest) final

def completedHistory (commits : List (Commit α)) :
    List (StackSpec.CompletedOperation α) :=
  commits.map Commit.completed

/--
The first linearizability lemma: successful Treiber commits implement the
sequential stack specification.

The future bridge theorem will extract these commits from every execution graph
allowed by the release-acquire model.
-/
theorem commitTrace_linearizable {initial final : List α}
    {commits : List (Commit α)}
    (trace : CommitTrace initial commits final) :
    StackSpec.Legal initial (completedHistory commits) final := by
  induction trace with
  | nil stack =>
      exact StackSpec.Legal.nil stack
  | cons commit rest headStep tailTrace inductionHypothesis =>
      exact StackSpec.Legal.cons
        commit.completed
        (completedHistory rest)
        (commitStep_matchesSpec headStep)
        inductionHypothesis

example : CommitTrace ([] : List Nat)
    [.push 7, .push 11, .popValue 11, .popValue 7, .popEmpty] [] := by
  exact .cons (.push 7) _ (.push 7 []) <|
    .cons (.push 11) _ (.push 11 [7]) <|
    .cons (.popValue 11) _ (.popValue 11 [7]) <|
    .cons (.popValue 7) _ (.popValue 7 []) <|
    .cons .popEmpty _ .popEmpty (.nil [])

end Treiber

end WeakMemory
