import WeakMemory.MSQueueSource

namespace WeakMemory.MSQueue.Source

/-!
# Global source-trace well-formedness

`LocalStep` checks one thread at a time.  This module supplies the global
layer that prevents a raw list of labels from bypassing that source machine:
the dynamic RC11 carrier is exactly the atomic projection of the trace, every
thread projection is a `Run`, operation and node identities are fresh, and
empty-dequeue commit anchors resolve to an earlier null `next` read.

This layer deliberately does not choose reads-from or modification order.
Those are candidate-execution data checked by `MultiLocationRC11.Valid` in
the next layer.
-/

namespace TraceEvent

def atomicOccurrence? : TraceEvent Value → Option (AtomicOccurrence Value)
  | .atomic occurrence => some occurrence
  | _ => none

def invocationId? : TraceEvent Value → Option OperationId
  | .invokeEnqueue _ operation _ _ => some operation
  | .invokeDequeue _ operation => some operation
  | _ => none

def reservedNode? : TraceEvent Value → Option NodeId
  | .invokeEnqueue _ _ node _ => some node
  | _ => none

end TraceEvent

def atomicOccurrences
    (trace : List (TraceEvent Value)) : List (AtomicOccurrence Value) :=
  trace.filterMap TraceEvent.atomicOccurrence?

def atomicIds (trace : List (TraceEvent Value)) : List EventId :=
  (atomicOccurrences trace).map AtomicOccurrence.id

/-- Membership in the atomic projection is equivalent to membership of the
corresponding atomic source event. -/
theorem atomicEvent_mem_of_atomicOccurrence_mem
    {occurrence : AtomicOccurrence Value}
    {trace : List (TraceEvent Value)}
    (member : occurrence ∈ atomicOccurrences trace) :
    TraceEvent.atomic occurrence ∈ trace := by
  rcases List.mem_filterMap.mp member with
    ⟨event, eventMember, selected⟩
  cases event with
  | atomic emitted =>
      simp [TraceEvent.atomicOccurrence?] at selected
      simpa [selected] using eventMember
  | invokeEnqueue => simp [TraceEvent.atomicOccurrence?] at selected
  | initializePayload => simp [TraceEvent.atomicOccurrence?] at selected
  | invokeDequeue => simp [TraceEvent.atomicOccurrence?] at selected
  | readPayload => simp [TraceEvent.atomicOccurrence?] at selected
  | respondEnqueue => simp [TraceEvent.atomicOccurrence?] at selected
  | respondDequeue => simp [TraceEvent.atomicOccurrence?] at selected

/-- Dynamic IDs occupy the consecutive range beginning after three globals. -/
def canonicalDynamicIds
    (trace : List (TraceEvent Value)) : List EventId :=
  List.range' 3 (atomicOccurrences trace).length

def invocationIds (trace : List (TraceEvent Value)) : List OperationId :=
  trace.filterMap TraceEvent.invocationId?

def reservedNodes (trace : List (TraceEvent Value)) : List NodeId :=
  trace.filterMap TraceEvent.reservedNode?

/-- The source-order projection observed by one local machine. -/
def threadTrace
    (trace : List (TraceEvent Value))
    (thread : ThreadId) : List (TraceEvent Value) :=
  trace.filter (fun event => event.thread == thread)

/-- Atomic projection preserves the fact that one thread's source trace is a
sublist of the global carrier. -/
theorem atomicIds_threadTrace_sublist
    (trace : List (TraceEvent Value))
    (thread : ThreadId) :
    (atomicIds (threadTrace trace thread)).Sublist (atomicIds trace) := by
  exact ((List.filter_sublist
    (p := fun event => event.thread == thread)
    (l := trace)).filterMap TraceEvent.atomicOccurrence?).map
      AtomicOccurrence.id

/-- An ordered pair of atomic source events projects to the same ordered pair
of dynamic identifiers. -/
theorem atomicIds_pair_sublist_of_atomicEvents
    {first second : AtomicOccurrence Value}
    {trace : List (TraceEvent Value)}
    (orderedEvents :
      [TraceEvent.atomic first, TraceEvent.atomic second].Sublist trace) :
    [first.id, second.id].Sublist (atomicIds trace) := by
  have projected :=
    (orderedEvents.filterMap TraceEvent.atomicOccurrence?).map
      AtomicOccurrence.id
  simpa [atomicIds, atomicOccurrences,
    TraceEvent.atomicOccurrence?] using projected

def headInitializer (dummy : NodeId) :
    MultiLocationRC11.Atom Site Ptr where
  id := 0
  thread? := none
  location := .head
  access := .initial (.node dummy)
  order := .relaxed

def tailInitializer (dummy : NodeId) :
    MultiLocationRC11.Atom Site Ptr where
  id := 1
  thread? := none
  location := .tail
  access := .initial (.node dummy)
  order := .relaxed

def dummyNextInitializer (dummy : NodeId) :
    MultiLocationRC11.Atom Site Ptr where
  id := 2
  thread? := none
  location := .next dummy
  access := .initial .null
  order := .relaxed

def staticAtoms (dummy : NodeId) :
    List (MultiLocationRC11.Atom Site Ptr) :=
  [headInitializer dummy, tailInitializer dummy,
    dummyNextInitializer dummy]

/-- Exact RC11 carrier generated by the source trace. -/
def projectedAtoms
    (dummy : NodeId)
    (trace : List (TraceEvent Value)) :
    List (MultiLocationRC11.Atom Site Ptr) :=
  staticAtoms dummy ++
    (atomicOccurrences trace).map AtomicOccurrence.toRC11Atom

/--
Construct a candidate without admitting any atoms outside the checked source
trace.  RF and per-location MO remain explicit inputs rather than being
silently synthesized.
-/
def projectCandidate
    (dummy : NodeId)
    (trace : List (TraceEvent Value))
    (readSources : List (EventId × EventId))
    (modificationOrder : Site → List EventId) :
    MultiLocationRC11.Candidate Site Ptr where
  atoms := projectedAtoms dummy trace
  readSources := readSources
  modificationOrder := modificationOrder

/--
Raw source-carrier order between anchored points.  This is not yet the
linearization schedule: M3 must additionally connect the chosen schedule to
RC11 and the queue invariant.
-/
def CommitPointBefore
    (trace : List (TraceEvent Value))
    (first second : AtomicOccurrence.CommitRecord Value) : Prop :=
  MultiLocationRC11.IdBefore first.point second.point (atomicIds trace)

/-- Strict occurrence order for non-atomic source events. -/
def EventBefore
    (first second : TraceEvent Value)
    (trace : List (TraceEvent Value)) : Prop :=
  ∃ leading middle trailing,
    trace = leading ++ [first] ++ middle ++ [second] ++ trailing

namespace EventBefore

theorem first_mem
    {first second : TraceEvent Value}
    {trace : List (TraceEvent Value)}
    (before : EventBefore first second trace) :
    first ∈ trace := by
  rcases before with ⟨leading, middle, trailing, rfl⟩
  simp

theorem second_mem
    {first second : TraceEvent Value}
    {trace : List (TraceEvent Value)}
    (before : EventBefore first second trace) :
    second ∈ trace := by
  rcases before with ⟨leading, middle, trailing, rfl⟩
  simp

end EventBefore

/--
Global source invariants not expressible by a single-thread `Run`.

No-reclamation is syntactic: `TraceEvent` contains neither `free` nor a reuse
event.  `reservedNodesNodup` strengthens that boundary by forbidding a node
identity from being reserved by two enqueue invocations.
-/
structure SourceWellFormed
    (dummy : NodeId)
    (trace : List (TraceEvent Value)) : Prop where
  atomicIdsCanonical :
    atomicIds trace = canonicalDynamicIds trace
  invocationIdsNodup :
    (invocationIds trace).Nodup
  reservedNodesNodup :
    (reservedNodes trace).Nodup
  dummyNotReserved :
    dummy ∉ reservedNodes trace
  threadRuns :
    ∀ thread,
      ∃ final,
        Run thread (.idle : LocalState Value)
          (threadTrace trace thread) final
  payloadInitializationMatches :
    ∀ {thread operation node value},
      TraceEvent.initializePayload thread operation node value ∈ trace →
        TraceEvent.invokeEnqueue thread operation node value ∈ trace
  nextInitializationMatches :
    ∀ {id thread operation node},
      TraceEvent.atomic
          ⟨id, AtomicAction.initializeNext thread operation node⟩ ∈ trace →
        ∃ value,
          TraceEvent.invokeEnqueue thread operation node value ∈ trace
  payloadReadInitialized :
    ∀ {index : Nat}
      {thread : ThreadId} {operation : OperationId}
      {node : NodeId} {value : Value},
      (TraceEvent.readPayload thread operation node value, index) ∈
          trace.zipIdx →
        ∃ (owner : ThreadId) (invocation : OperationId)
          (initializationIndex : Nat),
          initializationIndex < index ∧
            (TraceEvent.initializePayload owner invocation node value,
              initializationIndex) ∈ trace.zipIdx
  emptyAnchor :
    ∀ {validation thread operation head point},
      TraceEvent.atomic
          ⟨validation,
            AtomicAction.dequeueHeadValidateEmpty
              thread operation head point⟩ ∈ trace →
        TraceEvent.atomic
            ⟨point,
              AtomicAction.dequeueNextLoad
                thread operation head .null⟩ ∈ trace ∧
          MultiLocationRC11.IdBefore point validation (atomicIds trace)

/--
A source-backed finite RC11 execution.  The candidate is definitionally
constructed by `projectCandidate`, so a proof cannot smuggle in atoms that do
not come from the three static initializers or a checked source occurrence.
-/
structure SupportedExecution
    (dummy : NodeId)
    (trace : List (TraceEvent Value)) where
  sourceWellFormed : SourceWellFormed dummy trace
  readSources : List (EventId × EventId)
  modificationOrder : Site → List EventId
  valid :
    MultiLocationRC11.Valid
      (projectCandidate dummy trace readSources modificationOrder)

namespace SupportedExecution

def candidate
    (execution : SupportedExecution dummy trace) :
    MultiLocationRC11.Candidate Site Ptr :=
  projectCandidate dummy trace execution.readSources
    execution.modificationOrder

theorem atoms_exact
    (execution : SupportedExecution dummy trace) :
    execution.candidate.atoms = projectedAtoms dummy trace :=
  rfl

end SupportedExecution

namespace SourceWellFormed

/-- Every projected dynamic atom was emitted by an actual local source step. -/
theorem atomicGenerated
    {dummy : NodeId}
    {trace : List (TraceEvent Value)}
    (wellFormed : SourceWellFormed dummy trace)
    {occurrence : AtomicOccurrence Value}
    (member : TraceEvent.atomic occurrence ∈ trace) :
    ∃ before after,
      LocalStep occurrence.action.thread before
        (.atomic occurrence) after := by
  obtain ⟨final, run⟩ :=
    wellFormed.threadRuns occurrence.action.thread
  apply run.localStep_of_mem
  simp [threadTrace, member, TraceEvent.thread]

/-- In particular, exact-carrier construction cannot contain malformed success. -/
theorem atomic_not_malformedSuccess
    {dummy : NodeId}
    {trace : List (TraceEvent Value)}
    (wellFormed : SourceWellFormed dummy trace)
    {occurrence : AtomicOccurrence Value}
    (member : TraceEvent.atomic occurrence ∈ trace) :
    ¬ occurrence.action.IsMalformedSuccess := by
  obtain ⟨before, after, step⟩ := wellFormed.atomicGenerated member
  exact step.not_malformedSuccess

theorem atomicIdsNodup
    {dummy : NodeId}
    {trace : List (TraceEvent Value)}
    (wellFormed : SourceWellFormed dummy trace) :
    (atomicIds trace).Nodup := by
  rw [wellFormed.atomicIdsCanonical]
  exact List.nodup_range'

/-- Source-event sublist order induces strict dynamic-ID carrier order. -/
theorem idBefore_of_atomicEvents_sublist
    {dummy : NodeId}
    {trace : List (TraceEvent Value)}
    (wellFormed : SourceWellFormed dummy trace)
    {first second : AtomicOccurrence Value}
    (orderedEvents :
      [TraceEvent.atomic first, TraceEvent.atomic second].Sublist trace) :
    MultiLocationRC11.IdBefore first.id second.id (atomicIds trace) :=
  MultiLocationRC11.IdBefore.of_pair_sublist
    wellFormed.atomicIdsNodup
    (atomicIds_pair_sublist_of_atomicEvents orderedEvents)

/-- Canonical dynamic identifiers cannot collide with IDs `0`, `1`, or `2`. -/
theorem staticId_not_mem_atomicIds
    {dummy : NodeId}
    {trace : List (TraceEvent Value)}
    (wellFormed : SourceWellFormed dummy trace)
    {id : EventId}
    (isStatic : id < 3) :
    id ∉ atomicIds trace := by
  rw [wellFormed.atomicIdsCanonical]
  intro member
  have bounds :
      3 ≤ id ∧ id < 3 + (atomicOccurrences trace).length := by
    simpa [canonicalDynamicIds] using member
  exact (Nat.not_lt_of_ge bounds.1) isStatic

/-- The foreign key of every empty commit is a carrier-ordered null read. -/
theorem emptyPointBeforeValidation
    {dummy : NodeId}
    {trace : List (TraceEvent Value)}
    (wellFormed : SourceWellFormed dummy trace)
    {validation thread operation head point}
    (member :
      TraceEvent.atomic
          ⟨validation,
            AtomicAction.dequeueHeadValidateEmpty
              thread operation head point⟩ ∈ trace) :
    MultiLocationRC11.IdBefore point validation (atomicIds trace) :=
  (wellFormed.emptyAnchor member).2

end SourceWellFormed

namespace SupportedExecution

/-- Every projected dynamic occurrence belongs to the exact candidate. -/
theorem atomicAtom_mem
    {dummy : NodeId}
    {trace : List (TraceEvent Value)}
    (execution : SupportedExecution (Value := Value) dummy trace)
    {occurrence : AtomicOccurrence Value}
    (member : occurrence ∈ atomicOccurrences trace) :
    occurrence.toRC11Atom ∈ execution.candidate.atoms := by
  rw [execution.atoms_exact, projectedAtoms]
  exact List.mem_append.mpr
    (Or.inr (List.mem_map.mpr ⟨occurrence, member, rfl⟩))

/-- Dynamic source order lifts through the three static candidate atoms. -/
theorem dynamicIdBefore
    {dummy : NodeId}
    {trace : List (TraceEvent Value)}
    (execution : SupportedExecution (Value := Value) dummy trace)
    {first second : EventId}
    (before :
      MultiLocationRC11.IdBefore first second (atomicIds trace)) :
    MultiLocationRC11.IdBefore first second execution.candidate.atomIds := by
  have afterTwo := MultiLocationRC11.IdBefore.cons
    (head := 2)
    (execution.sourceWellFormed.staticId_not_mem_atomicIds (id := 2)
      (by decide)) before
  have oneFresh : (1 : EventId) ∉ 2 :: atomicIds trace := by
    simp only [List.mem_cons, not_or]
    exact ⟨by decide,
      execution.sourceWellFormed.staticId_not_mem_atomicIds (id := 1)
        (by decide)⟩
  have afterOne := MultiLocationRC11.IdBefore.cons
    (head := 1) oneFresh afterTwo
  have zeroFresh : (0 : EventId) ∉ 1 :: 2 :: atomicIds trace := by
    simp only [List.mem_cons, not_or]
    exact ⟨by decide, by decide,
      execution.sourceWellFormed.staticId_not_mem_atomicIds (id := 0)
        (by decide)⟩
  have afterZero := MultiLocationRC11.IdBefore.cons
    (head := 0) zeroFresh afterOne
  change MultiLocationRC11.IdBefore first second
    ((projectedAtoms dummy trace).map MultiLocationRC11.Atom.id)
  rw [projectedAtoms, List.map_append]
  simpa [staticAtoms, headInitializer, tailInitializer,
    dummyNextInitializer, atomicIds, List.map_map,
    Function.comp_def, AtomicOccurrence.toRC11Atom] using afterZero

/-- Same-thread dynamic carrier order is a typed RC11 program-order edge. -/
theorem programOrder_of_atomicIdBefore
    {dummy : NodeId}
    {trace : List (TraceEvent Value)}
    (execution : SupportedExecution (Value := Value) dummy trace)
    {first second : AtomicOccurrence Value}
    (firstMember : first ∈ atomicOccurrences trace)
    (secondMember : second ∈ atomicOccurrences trace)
    (sameThread : first.action.thread = second.action.thread)
    (before :
      MultiLocationRC11.IdBefore first.id second.id (atomicIds trace)) :
    MultiLocationRC11.PO execution.candidate
      first.toRC11Atom second.toRC11Atom := by
  refine ⟨execution.atomicAtom_mem firstMember,
    execution.atomicAtom_mem secondMember, Or.inr ?_⟩
  refine ⟨first.action.thread, ?_, ?_, execution.dynamicIdBefore before⟩
  · rfl
  · simpa [AtomicOccurrence.toRC11Atom] using congrArg some sameThread.symm

end SupportedExecution

end WeakMemory.MSQueue.Source
