import WeakMemory.TreiberProgramDescriptor

/-!
This file is generated by
`tools/extract_treiber_source_trust_boundary.py`.

Do not edit it manually.  The value below crosses an explicitly trusted,
unproved Clang-AST extraction boundary; it is not evidence of a proved C
semantics frontend.
-/

namespace WeakMemory.TreiberProgramDescriptor.Extracted

/-- Hash-pinned facts extracted from the current reclamation-free C source. -/
def treiberProgram : PinnedExtraction where
  schema := "treiber-source-extraction-trust-boundary/v1"
  clangVersion := "18.1.3"
  cSourceSha256 := "7a0ef93f9510ae71873d930f7e06a8bb36416a6b33587a814fe779c3b5e56d13"
  cHeaderSha256 := "0f32a0ca76a95891308662143e609c6da03eab49c7254b8ce058fd464ff2d882"
  descriptor := {
    initializesHeadToNull := true
    pushLoadOrder := .relaxed
    popLoadOrder := .acquire
    isEmptyLoadOrder := .acquire
    pushCompareExchange := {
      strength := .weak
      successOrder := .release
      failureOrder := .relaxed
      failureUpdatesExpected := true
    }
    popCompareExchange := {
      strength := .weak
      successOrder := .acquire
      failureOrder := .acquire
      failureUpdatesExpected := true
    }
    pushNextBehavior := .pushWritesObservedBeforeEveryAttempt
    popNextBehavior := .popReadsObservedNextBeforeEveryNonNullAttempt
    pushRetryBehavior := .pushUpdatesExpectedThenRewritesNext
    popRetryBehavior := .popUpdatesExpectedThenReadsNextOrReturnsNull
    pushReturnBehavior := .pushReturnsVoidAfterSuccess
    popReturnBehavior := .popReturnsObservedOnSuccessOrNullWhenEmpty
    isEmptyReturnBehavior := .isEmptyReturnsHeadNullTest
  }

end WeakMemory.TreiberProgramDescriptor.Extracted
