import WeakMemory.TreiberRA

namespace WeakMemory.TreiberRC11

/-!
# An RC11-style execution-graph layer for Treiber's stack

This module begins the second bridge in the verification:

```text
RC11-style execution graph
            ↓
operational RA Treiber execution
            ↓
legal sequential stack history
```

It formalizes a finite, single-atomic-location fragment containing:

* program order (`po`);
* reads-from (`rf`);
* modification order (`mo`);
* release/acquire synchronization;
* happens-before;
* functional reads-from;
* a strict total modification order on writes;
* the immediate-predecessor rule for successful read-modify-write events.

This is not yet the complete ISO C11/RC11 model. In particular, the theorem
that every well-formed graph admits a certified operational schedule remains a
separate proof obligation. The final theorem in this file is conditional on
such a schedule and composes it with the already-proved operational result.
-/

abbrev EventId := Nat

/-- The initial head write or one event generated by the Treiber algorithm. -/
inductive EventKind (α : Type) where
  | initial
  | algorithm : TreiberRA.Action α → EventKind α
  deriving Repr, DecidableEq

structure Event (α : Type) where
  id : EventId
  kind : EventKind α
  deriving Repr, DecidableEq

namespace Event

def action? : Event α → Option (TreiberRA.Action α)
  | ⟨_, .initial⟩ => none
  | ⟨_, .algorithm action⟩ => some action

def thread? : Event α → Option Nat
  | ⟨_, .initial⟩ => none
  | ⟨_, .algorithm action⟩ =>
      match action with
      | .pushSuccess thread .. => some thread
      | .pushFailure thread .. => some thread
      | .popSuccess thread .. => some thread
      | .popFailure thread .. => some thread
      | .popEmpty thread => some thread

/--
The value read from the atomic head.

The outer `Option` says whether the event reads. The inner `Option NodeId` is
the pointer value, where `none` is the null head.
-/
def readValue : Event α → Option (Option TreiberRA.NodeId)
  | ⟨_, .initial⟩ => none
  | ⟨_, .algorithm action⟩ =>
      match action with
      | .pushSuccess _ _ _ expected => some expected
      | .pushFailure _ _ _ _ actual => some actual
      | .popSuccess _ nodeId _ _ => some (some nodeId)
      | .popFailure _ _ actual => some actual
      | .popEmpty _ => some none

/-- The value written to the atomic head, if this event modifies it. -/
def writtenValue : Event α → Option (Option TreiberRA.NodeId)
  | ⟨_, .initial⟩ => some none
  | ⟨_, .algorithm action⟩ =>
      match action with
      | .pushSuccess _ nodeId _ _ => some (some nodeId)
      | .popSuccess _ _ _ next => some next
      | .pushFailure .. | .popFailure .. | .popEmpty .. => none

def order : Event α → MemoryOrder
  | ⟨_, .initial⟩ => .relaxed
  | ⟨_, .algorithm action⟩ => action.order

def IsRead (event : Event α) : Prop :=
  ∃ value, event.readValue = some value

def IsWrite (event : Event α) : Prop :=
  ∃ value, event.writtenValue = some value

/-- Successful compare-exchanges are the RMW events in this fragment. -/
def IsRMW : Event α → Prop
  | ⟨_, .algorithm (.pushSuccess ..)⟩ => True
  | ⟨_, .algorithm (.popSuccess ..)⟩ => True
  | _ => False

def IsInitial : Event α → Prop
  | ⟨_, .initial⟩ => True
  | _ => False

theorem action_order {event : Event α} {action : TreiberRA.Action α}
    (projects : event.action? = some action) :
    event.order = action.order := by
  cases event with
  | mk id kind =>
      cases kind with
      | initial =>
          simp [action?] at projects
      | algorithm projected =>
          simp [action?] at projects
          cases projects
          rfl

end Event

/-- A finite candidate execution graph for the single atomic head location. -/
structure Graph (α : Type) where
  events : List (Event α)
  programOrder : Relation (Event α)
  readsFrom : Relation (Event α)
  modificationOrder : Relation (Event α)

namespace Graph

/-- Two modifications are adjacent in the single-location modification order. -/
def ImmediateModification (graph : Graph α)
    (source target : Event α) : Prop :=
  source ∈ graph.events ∧
    target ∈ graph.events ∧
    graph.modificationOrder source target ∧
    ∀ middle,
      middle ∈ graph.events →
      middle.IsWrite →
      ¬ (graph.modificationOrder source middle ∧
        graph.modificationOrder middle target)

/--
The RMW-only release-sequence fragment used by the Treiber implementation.

The release property is checked separately at the head of the sequence.
-/
inductive ReleaseSequence (graph : Graph α)
    (head : Event α) : Event α → Prop where
  | head (member : head ∈ graph.events) :
      ReleaseSequence graph head head
  | rmw {previous next} :
      ReleaseSequence graph head previous →
      graph.ImmediateModification previous next →
      next.IsRMW →
      ReleaseSequence graph head next

def synchronizesWith (graph : Graph α)
    (release acquire : Event α) : Prop :=
  ∃ source,
    graph.ReleaseSequence release source ∧
    graph.readsFrom source acquire ∧
    release.order.hasRelease = true ∧
    acquire.order.hasAcquire = true

/-- Happens-before is generated by program order and synchronizes-with. -/
inductive HappensBefore (graph : Graph α) : Relation (Event α) where
  | programOrder {source target} :
      graph.programOrder source target →
      HappensBefore graph source target
  | synchronizesWith {source target} :
      graph.synchronizesWith source target →
      HappensBefore graph source target
  | transitive {first middle last} :
      HappensBefore graph first middle →
      HappensBefore graph middle last →
      HappensBefore graph first last

end Graph

def Acyclic (relation : Relation α) : Prop :=
  ∀ element, ¬ relation element element

/--
Well-formedness conditions for the current single-location RC11-style core.

These conditions are intentionally named individually so later work can audit
which parts correspond to RC11 axioms and which are Treiber-specific.
-/
structure WellFormed (graph : Graph α) : Prop where
  uniqueIds :
    ∀ {left right},
      left ∈ graph.events →
      right ∈ graph.events →
      left.id = right.id →
      left = right
  programOrderClosed :
    ∀ {source target},
      graph.programOrder source target →
      source ∈ graph.events ∧ target ∈ graph.events
  programOrderSameThread :
    ∀ {source target},
      graph.programOrder source target →
      ∃ thread,
        source.thread? = some thread ∧
        target.thread? = some thread
  programOrderIrreflexive :
    ∀ event, ¬ graph.programOrder event event
  programOrderTransitive :
    ∀ {first middle last},
      graph.programOrder first middle →
      graph.programOrder middle last →
      graph.programOrder first last
  readsFromClosed :
    ∀ {source target},
      graph.readsFrom source target →
      source ∈ graph.events ∧ target ∈ graph.events
  modificationOrderClosed :
    ∀ {source target},
      graph.modificationOrder source target →
      source ∈ graph.events ∧ target ∈ graph.events
  readsFromValues :
    ∀ {source target},
      graph.readsFrom source target →
      ∃ value,
        source.writtenValue = some value ∧
        target.readValue = some value
  readsFromFunctional :
    ∀ {firstSource secondSource target},
      graph.readsFrom firstSource target →
      graph.readsFrom secondSource target →
      firstSource = secondSource
  everyReadHasSource :
    ∀ {target},
      target ∈ graph.events →
      target.IsRead →
      ∃ source, graph.readsFrom source target
  modificationOrderWrites :
    ∀ {source target},
      graph.modificationOrder source target →
      source.IsWrite ∧ target.IsWrite
  modificationOrderIrreflexive :
    ∀ event, ¬ graph.modificationOrder event event
  modificationOrderTransitive :
    ∀ {first middle last},
      graph.modificationOrder first middle →
      graph.modificationOrder middle last →
      graph.modificationOrder first last
  modificationOrderTotal :
    ∀ {left right},
      left ∈ graph.events →
      right ∈ graph.events →
      left.IsWrite →
      right.IsWrite →
      left ≠ right →
      graph.modificationOrder left right ∨
        graph.modificationOrder right left
  initialExistsUnique :
    ∃ initial,
      initial ∈ graph.events ∧
      initial.IsInitial ∧
      ∀ other,
        other ∈ graph.events →
        other.IsInitial →
        other = initial
  initialPrecedesWrites :
    ∀ {initial write},
      initial ∈ graph.events →
      initial.IsInitial →
      write ∈ graph.events →
      write.IsWrite →
      ¬ write.IsInitial →
      graph.modificationOrder initial write
  rmwReadsImmediatePredecessor :
    ∀ {source rmw},
      graph.readsFrom source rmw →
      rmw.IsRMW →
      graph.modificationOrder source rmw ∧
        ∀ middle,
          middle ∈ graph.events →
          middle.IsWrite →
          ¬ (graph.modificationOrder source middle ∧
            graph.modificationOrder middle rmw)
  happensBeforeAcyclic :
    Acyclic graph.HappensBefore

namespace WellFormed

theorem readsFrom_preservesValue {graph : Graph α}
    (wellFormed : WellFormed graph)
    {source target : Event α}
    (readsFrom : graph.readsFrom source target) :
    ∃ value,
      source.writtenValue = some value ∧
      target.readValue = some value :=
  wellFormed.readsFromValues readsFrom

theorem readsFrom_source_unique {graph : Graph α}
    (wellFormed : WellFormed graph)
    {firstSource secondSource target : Event α}
    (firstReadsFrom : graph.readsFrom firstSource target)
    (secondReadsFrom : graph.readsFrom secondSource target) :
    firstSource = secondSource :=
  wellFormed.readsFromFunctional firstReadsFrom secondReadsFrom

theorem rmw_source_precedes {graph : Graph α}
    (wellFormed : WellFormed graph)
    {source rmw : Event α}
    (readsFrom : graph.readsFrom source rmw)
    (isRMW : rmw.IsRMW) :
    graph.modificationOrder source rmw :=
  (wellFormed.rmwReadsImmediatePredecessor readsFrom isRMW).1

theorem rmw_hasNoInterveningWrite {graph : Graph α}
    (wellFormed : WellFormed graph)
    {source rmw middle : Event α}
    (readsFrom : graph.readsFrom source rmw)
    (isRMW : rmw.IsRMW)
    (middleMember : middle ∈ graph.events)
    (middleWrites : middle.IsWrite) :
    ¬ (graph.modificationOrder source middle ∧
      graph.modificationOrder middle rmw) :=
  (wellFormed.rmwReadsImmediatePredecessor readsFrom isRMW).2
    middle middleMember middleWrites

theorem rmw_readsFrom_immediateModification {graph : Graph α}
    (wellFormed : WellFormed graph)
    {source rmw : Event α}
    (readsFrom : graph.readsFrom source rmw)
    (isRMW : rmw.IsRMW) :
    graph.ImmediateModification source rmw := by
  have endpoints := wellFormed.readsFromClosed readsFrom
  refine ⟨endpoints.1, endpoints.2,
    wellFormed.rmw_source_precedes readsFrom isRMW, ?_⟩
  intro middle middleMember middleWrites
  exact wellFormed.rmw_hasNoInterveningWrite readsFrom isRMW
    middleMember middleWrites

end WellFormed

namespace Graph.ReleaseSequence

theorem headMember {graph : Graph α} {head source : Event α}
    (sequence : graph.ReleaseSequence head source) :
    head ∈ graph.events := by
  induction sequence with
  | head member =>
      exact member
  | rmw previousSequence immediate isRMW inductionHypothesis =>
      exact inductionHypothesis

theorem sourceMember {graph : Graph α} {head source : Event α}
    (sequence : graph.ReleaseSequence head source) :
    source ∈ graph.events := by
  cases sequence with
  | head member =>
      exact member
  | rmw previousSequence immediate isRMW =>
      exact immediate.2.1

/-- A nontrivial release sequence follows modification order from its head. -/
theorem equalOrPrecedes {graph : Graph α}
    (wellFormed : WellFormed graph)
    {head source : Event α}
    (sequence : graph.ReleaseSequence head source) :
    head = source ∨ graph.modificationOrder head source := by
  induction sequence with
  | head member =>
      exact Or.inl rfl
  | @rmw previous next previousSequence immediate isRMW
      inductionHypothesis =>
      cases inductionHypothesis with
      | inl equal =>
          subst previous
          exact Or.inr immediate.2.2.1
      | inr headBeforePrevious =>
          exact Or.inr (wellFormed.modificationOrderTransitive
            headBeforePrevious immediate.2.2.1)

end Graph.ReleaseSequence

theorem releaseAcquireReadsFrom_isHappensBefore
    {graph : Graph α}
    (wellFormed : WellFormed graph)
    {source target : Event α}
    (readsFrom : graph.readsFrom source target)
    (sourceReleases : source.order.hasRelease = true)
    (targetAcquires : target.order.hasAcquire = true) :
    graph.HappensBefore source target := by
  apply Graph.HappensBefore.synchronizesWith
  exact ⟨source,
    Graph.ReleaseSequence.head (wellFormed.readsFromClosed readsFrom).1,
    readsFrom,
    sourceReleases, targetAcquires⟩

theorem releaseSequenceAcquire_isHappensBefore
    (graph : Graph α) {release source target : Event α}
    (releaseSequence : graph.ReleaseSequence release source)
    (readsFrom : graph.readsFrom source target)
    (releaseReleases : release.order.hasRelease = true)
    (targetAcquires : target.order.hasAcquire = true) :
    graph.HappensBefore release target := by
  apply Graph.HappensBefore.synchronizesWith
  exact ⟨source, releaseSequence, readsFrom,
    releaseReleases, targetAcquires⟩

/--
No release/acquire reads-from edge can point back to itself in a well-formed
graph, as that would create a happens-before cycle.
-/
theorem noSelfSynchronizesWith {graph : Graph α}
    (wellFormed : WellFormed graph) (event : Event α) :
    ¬ graph.synchronizesWith event event := by
  intro selfEdge
  apply wellFormed.happensBeforeAcyclic event
  exact Graph.HappensBefore.synchronizesWith selfEdge

/--
An event schedule lists graph events in the order chosen for the operational
simulation. Initial events do not project to algorithm actions.
-/
def projectedActions : List (Event α) → List (TreiberRA.Action α)
  | [] => []
  | event :: rest =>
      match event.action? with
      | none => projectedActions rest
      | some action => action :: projectedActions rest

/--
A scheduled execution certifies that every scheduled algorithm event belongs
to the graph and performs the corresponding operational Treiber step.
-/
inductive ScheduledExecution (graph : Graph α) :
    TreiberRA.State α →
    List (Event α) →
    TreiberRA.State α →
    Prop where
  | nil (state : TreiberRA.State α) :
      ScheduledExecution graph state [] state
  | initial {initial final : TreiberRA.State α}
      (event : Event α)
      (rest : List (Event α))
      (member : event ∈ graph.events)
      (isInitial : event.IsInitial)
      (later : ScheduledExecution graph initial rest final) :
      ScheduledExecution graph initial (event :: rest) final
  | algorithm {initial middle final : TreiberRA.State α}
      (event : Event α)
      (rest : List (Event α))
      (action : TreiberRA.Action α)
      (member : event ∈ graph.events)
      (projects : event.action? = some action)
      (first : TreiberRA.Step initial action middle)
      (later : ScheduledExecution graph middle rest final) :
      ScheduledExecution graph initial (event :: rest) final

/-- A graph event appears before another event in a proposed schedule. -/
def Before (first second : Event α) (schedule : List (Event α)) : Prop :=
  ∃ earlier between later,
    schedule = earlier ++ first :: between ++ second :: later

/--
The schedule covers every graph event exactly once and respects both `po` and
`mo`. This certificate is the target of the future graph-linearization proof.
-/
structure RespectsGraph (graph : Graph α)
    (schedule : List (Event α)) : Prop where
  covers :
    ∀ event, event ∈ graph.events ↔ event ∈ schedule
  noDuplicates :
    schedule.Nodup
  programOrder :
    ∀ {source target},
      graph.programOrder source target →
      Before source target schedule
  modificationOrder :
    ∀ {source target},
      graph.modificationOrder source target →
      Before source target schedule

structure CertifiedSchedule (graph : Graph α)
    (initial : TreiberRA.State α)
    (schedule : List (Event α))
    (final : TreiberRA.State α) : Prop where
  respectsGraph : RespectsGraph graph schedule
  executes : ScheduledExecution graph initial schedule final

/-- A scheduled graph execution is an operational RA execution. -/
theorem scheduledExecution_toAllowedExecution
    {graph : Graph α}
    {initial final : TreiberRA.State α}
    {schedule : List (Event α)}
    (execution : ScheduledExecution graph initial schedule final) :
    TreiberRA.AllowedExecution initial
      (projectedActions schedule) final := by
  induction execution with
  | nil state =>
      exact TreiberRA.AllowedExecution.nil state
  | initial event rest member isInitial later inductionHypothesis =>
      cases event with
      | mk id kind =>
          cases kind with
          | initial =>
              simpa [projectedActions, Event.action?] using
                inductionHypothesis
          | algorithm action =>
              simp [Event.IsInitial] at isInitial
  | algorithm event rest action member projects first later
      inductionHypothesis =>
      simp only [projectedActions, projects]
      exact TreiberRA.AllowedExecution.cons action
        (projectedActions rest) first inductionHypothesis

/--
The first graph-to-operational composition theorem.

Once the future existence proof constructs a `CertifiedSchedule` from graph
well-formedness, this theorem immediately yields the sequential specification.
-/
theorem certifiedSchedule_linearizable
    {graph : Graph α}
    {initial final : TreiberRA.State α}
    {schedule : List (Event α)}
    {initialValues : List α}
    (certificate : CertifiedSchedule graph initial schedule final)
    (initialRepresentation :
      TreiberRA.Represents initial.heap initial.head initialValues) :
    ∃ finalValues,
      TreiberRA.Represents final.heap final.head finalValues ∧
      StackSpec.Legal initialValues
        (Treiber.completedHistory
          (TreiberRA.commits (projectedActions schedule)))
        finalValues := by
  apply TreiberRA.allowedExecution_linearizable
  · exact scheduledExecution_toAllowedExecution certificate.executes
  · exact initialRepresentation

end WeakMemory.TreiberRC11
