import WeakMemory.TreiberInterleaving

namespace WeakMemory.TreiberRC11

/-!
# Source-controlled generated candidates

This module joins two existing, deliberately separate certificates:

* `Interleaving.SourceSkeleton` checks per-thread invocation and retry control
  flow, unique operation identifiers, and fresh distinct push reservations;
* `GeneratedEvents` checks allocator construction and local graph-event
  typing.

The generated event list is exactly the event carrier projected from the
source skeleton. A permutation connects that construction order to the graph
carrier, and an equality requires graph program order to be precisely the
program order generated by `EventGraph.Skeleton`.

Reads-from and modification order remain fields of the supplied graph. This
module neither generates those relations nor claims a complete C11 or
source-language semantics.
-/

/-- A source skeleton together with its global interleaving certificate. -/
structure ControlledSource
    (initial : TreiberRA.State α) where
  skeleton :
    EventGraph.Skeleton α
  valid :
    Interleaving.SourceSkeleton initial skeleton

/--
A graph candidate controlled by one certified source skeleton.

`generated` is indexed by `source.skeleton.events` directly, preventing a
second unrelated event list from entering the certificate.
-/
structure ControlledCandidate
    (graph : Graph α)
    (initial : TreiberRA.State α) where
  source :
    ControlledSource initial
  allocator :
    AllocatorTable α
  initialHeadEmpty :
    initial.head = none
  generated :
    GeneratedEvents graph initial allocator
      source.skeleton.events
  eventsPermutation :
    source.skeleton.events.Perm graph.events
  programOrder_eq :
    graph.programOrder =
      source.skeleton.programOrder

/--
The graph fields constructed directly from a controlled source skeleton.

This is intentionally only a subset of `WellFormed`; reads-from,
modification-order, RMW, happens-before, and coherence obligations are absent.
-/
structure CarrierProgramOrderWellFormed
    (graph : Graph α) : Prop where
  noDuplicateEvents :
    graph.events.Nodup
  uniqueIds :
    ∀ {left right},
      left ∈ graph.events →
      right ∈ graph.events →
      left.id = right.id →
      left = right
  initialExistsUnique :
    ∃ initial,
      initial ∈ graph.events ∧
        initial.IsInitial ∧
        ∀ other,
          other ∈ graph.events →
          other.IsInitial →
          other = initial
  programOrderClosed :
    ∀ {source target},
      graph.programOrder source target →
      source ∈ graph.events ∧ target ∈ graph.events
  programOrderSameThread :
    ∀ {source target},
      graph.programOrder source target →
      ∃ thread,
        source.thread? = some thread ∧
        target.thread? = some thread
  programOrderIrreflexive :
    ∀ event,
      ¬ graph.programOrder event event
  programOrderTransitive :
    ∀ {first middle last},
      graph.programOrder first middle →
      graph.programOrder middle last →
      graph.programOrder first last

namespace ControlledCandidate

/-- Forget source-control metadata while retaining the generated candidate. -/
def toGeneratedCandidate
    {graph : Graph α}
    {initial : TreiberRA.State α}
    (candidate : ControlledCandidate graph initial) :
    GeneratedCandidate graph initial where
  allocator := candidate.allocator
  emitted := candidate.source.skeleton.events
  initialHeadEmpty := candidate.initialHeadEmpty
  generated := candidate.generated
  eventsPermutation := candidate.eventsPermutation

/-- Every source-controlled candidate has the existing graph typing. -/
def toGraphTyping
    {graph : Graph α}
    {initial : TreiberRA.State α}
    (candidate : ControlledCandidate graph initial) :
    GraphTyping graph initial :=
  candidate.toGeneratedCandidate.toGraphTyping

/-- The actual graph carrier is duplicate-free. -/
theorem noDuplicateEvents
    {graph : Graph α}
    {initial : TreiberRA.State α}
    (candidate : ControlledCandidate graph initial) :
    graph.events.Nodup :=
  candidate.eventsPermutation.nodup
    candidate.source.skeleton.noDuplicateEvents

/-- Event identifiers are injective on the actual graph carrier. -/
theorem uniqueIds
    {graph : Graph α}
    {initial : TreiberRA.State α}
    (candidate : ControlledCandidate graph initial)
    {left right : Event α}
    (leftMember : left ∈ graph.events)
    (rightMember : right ∈ graph.events)
    (sameId : left.id = right.id) :
    left = right := by
  apply candidate.source.skeleton.uniqueIds
  · exact candidate.eventsPermutation.mem_iff.mpr leftMember
  · exact candidate.eventsPermutation.mem_iff.mpr rightMember
  · exact sameId

/-- The actual graph contains exactly one logical initializer. -/
theorem initialExistsUnique
    {graph : Graph α}
    {initialState : TreiberRA.State α}
    (candidate : ControlledCandidate graph initialState) :
    ∃ initial,
      initial ∈ graph.events ∧
        initial.IsInitial ∧
        ∀ other,
          other ∈ graph.events →
          other.IsInitial →
          other = initial := by
  obtain ⟨initial, initialMember, isInitial, unique⟩ :=
    candidate.source.skeleton.initialExistsUnique
  refine ⟨initial,
    candidate.eventsPermutation.mem_iff.mp initialMember,
    isInitial, ?_⟩
  intro other otherMember otherInitial
  exact unique other
    (candidate.eventsPermutation.mem_iff.mpr otherMember)
    otherInitial

/-- Actual graph program order is closed over its permuted carrier. -/
theorem programOrderClosed
    {graph : Graph α}
    {initial : TreiberRA.State α}
    (candidate : ControlledCandidate graph initial)
    {source target : Event α}
    (edge : graph.programOrder source target) :
    source ∈ graph.events ∧ target ∈ graph.events := by
  rw [candidate.programOrder_eq] at edge
  exact ⟨
    candidate.eventsPermutation.mem_iff.mp edge.1,
    candidate.eventsPermutation.mem_iff.mp edge.2.1⟩

/-- Actual graph program order relates events of one algorithm thread. -/
theorem programOrderSameThread
    {graph : Graph α}
    {initial : TreiberRA.State α}
    (candidate : ControlledCandidate graph initial)
    {source target : Event α}
    (edge : graph.programOrder source target) :
    ∃ thread,
      source.thread? = some thread ∧
        target.thread? = some thread := by
  rw [candidate.programOrder_eq] at edge
  exact ⟨edge.2.2.choose,
    edge.2.2.choose_spec.1,
    edge.2.2.choose_spec.2.1⟩

/-- Actual graph program order is irreflexive. -/
theorem programOrderIrreflexive
    {graph : Graph α}
    {initial : TreiberRA.State α}
    (candidate : ControlledCandidate graph initial)
    (event : Event α) :
    ¬ graph.programOrder event event := by
  rw [candidate.programOrder_eq]
  exact EventGraph.Skeleton.programOrderIrreflexive
    candidate.source.skeleton
    graph.readsFrom
    graph.modificationOrder
    event

/-- Actual graph program order is transitive. -/
theorem programOrderTransitive
    {graph : Graph α}
    {initial : TreiberRA.State α}
    (candidate : ControlledCandidate graph initial)
    {first middle last : Event α}
    (firstEdge : graph.programOrder first middle)
    (secondEdge : graph.programOrder middle last) :
    graph.programOrder first last := by
  rw [candidate.programOrder_eq] at firstEdge secondEdge ⊢
  exact EventGraph.Skeleton.programOrderTransitive
    candidate.source.skeleton
    graph.readsFrom
    graph.modificationOrder
    firstEdge
    secondEdge

/-- Bundle every carrier and program-order field constructed by the source. -/
theorem toCarrierProgramOrderWellFormed
    {graph : Graph α}
    {initial : TreiberRA.State α}
    (candidate : ControlledCandidate graph initial) :
    CarrierProgramOrderWellFormed graph where
  noDuplicateEvents :=
    candidate.noDuplicateEvents
  uniqueIds leftMember rightMember sameId :=
    candidate.uniqueIds leftMember rightMember sameId
  initialExistsUnique :=
    candidate.initialExistsUnique
  programOrderClosed edge :=
    candidate.programOrderClosed edge
  programOrderSameThread edge :=
    candidate.programOrderSameThread edge
  programOrderIrreflexive event :=
    candidate.programOrderIrreflexive event
  programOrderTransitive firstEdge secondEdge :=
    candidate.programOrderTransitive firstEdge secondEdge

end ControlledCandidate

namespace CoreConsistent

/--
A core-consistent source-controlled candidate yields a replay schedule and a
legal sequential stack history.

Scheduling acyclicity is derived by `CoreConsistent`; no separate acyclicity
premise is required. Core consistency still remains an explicit graph
obligation and, in particular, this theorem does not generate or validate
reads-from or modification order from C source.
-/
theorem linearizable_of_controlledCandidate
    [DecidableEq α]
    {graph : Graph α}
    {initial : TreiberRA.State α}
    {initialValues : List α}
    (consistent : CoreConsistent graph)
    (candidate : ControlledCandidate graph initial)
    (initialRepresentation :
      TreiberRA.Represents
        initial.heap initial.head initialValues) :
    ∃ schedule final finalValues,
      RespectsGraph graph schedule ∧
        replay? initial schedule = some final ∧
        TreiberRA.Represents
          final.heap final.head finalValues ∧
        StackSpec.Legal initialValues
          (Treiber.completedHistory
            (TreiberRA.commits
              (projectedActions schedule)))
          finalValues :=
  linearizable_of_generatedCandidate
    consistent
    candidate.toGeneratedCandidate
    initialRepresentation

end CoreConsistent

end WeakMemory.TreiberRC11
