import WeakMemory

namespace WeakMemory.TreiberProgramDescriptor

/-!
# Compact source-program descriptor

This module defines the stable data shape consumed by the generated Treiber
source descriptor.  It contains no parser and makes no claim about C
semantics.  `TreiberExtractedProgram` is generated by an explicitly trusted
Clang-AST extractor, while `TreiberProgramRefinement` checks the individual
descriptor components against the existing operational/control-flow model.
-/

/-- Compare-exchange strength at the C source boundary. -/
inductive CompareExchangeStrength where
  | weak
  | strong
  deriving Repr, DecidableEq

/-- The extracted orders and failure behavior of one compare-exchange. -/
structure CompareExchange where
  strength : CompareExchangeStrength
  successOrder : MemoryOrder
  failureOrder : MemoryOrder
  failureUpdatesExpected : Bool
  deriving Repr, DecidableEq

/-- Source-level access to the immutable `next` field around an attempt. -/
inductive NextBehavior where
  | pushWritesObservedBeforeEveryAttempt
  | popReadsObservedNextBeforeEveryNonNullAttempt
  deriving Repr, DecidableEq

/-- Source-level retry shape after a failed weak compare-exchange. -/
inductive RetryBehavior where
  | pushUpdatesExpectedThenRewritesNext
  | popUpdatesExpectedThenReadsNextOrReturnsNull
  deriving Repr, DecidableEq

/-- Client-visible return behavior of a source operation. -/
inductive ReturnBehavior where
  | pushReturnsVoidAfterSuccess
  | popReturnsObservedOnSuccessOrNullWhenEmpty
  | isEmptyReturnsHeadNullTest
  deriving Repr, DecidableEq

/--
The exact compact facts extracted from the reclamation-free Treiber source.
-/
structure Descriptor where
  initializesHeadToNull : Bool
  pushLoadOrder : MemoryOrder
  popLoadOrder : MemoryOrder
  isEmptyLoadOrder : MemoryOrder
  pushCompareExchange : CompareExchange
  popCompareExchange : CompareExchange
  pushNextBehavior : NextBehavior
  popNextBehavior : NextBehavior
  pushRetryBehavior : RetryBehavior
  popRetryBehavior : RetryBehavior
  pushReturnBehavior : ReturnBehavior
  popReturnBehavior : ReturnBehavior
  isEmptyReturnBehavior : ReturnBehavior
  deriving Repr, DecidableEq

/--
Hashes and frontend version attached to one generated descriptor.

Values of this type are evidence only about the explicitly trusted extraction
boundary.  They are not proof objects for the C11 abstract machine.
-/
structure PinnedExtraction where
  schema : String
  clangVersion : String
  cSourceSha256 : String
  cHeaderSha256 : String
  descriptor : Descriptor
  deriving Repr, DecidableEq

end WeakMemory.TreiberProgramDescriptor
