import WeakMemory.TreiberSourceExecution

namespace WeakMemory.TreiberRC11

/-!
# Release sequences from the concrete modification order

Every non-initial write in the current Treiber event universe is a successful
compare-exchange, hence an RMW.  The finite `AtomicRelationData.writeOrder`
therefore determines an RMW-only release sequence between any two
non-initial writes that are equal or ordered by modification order.
-/

namespace IdBefore

/-- No identifier can strictly precede the head of a list. -/
theorem notBeforeHead
    {first head : EventId}
    {tail : List EventId}
    (before : IdBefore first head (head :: tail)) :
    False := by
  have impossible :
      (head :: tail).idxOf first < 0 := by
    simpa using before.2.2
  exact (Nat.not_lt_zero _) impossible

/-- Remove a fresh list head from an order whose endpoints are in the tail. -/
theorem tail
    {first second head : EventId}
    {tail : List EventId}
    (headFresh : head ∉ tail)
    (firstMember : first ∈ tail)
    (secondMember : second ∈ tail)
    (before : IdBefore first second (head :: tail)) :
    IdBefore first second tail := by
  have headNeFirst : head ≠ first := by
    intro same
    subst first
    exact headFresh firstMember
  have headNeSecond : head ≠ second := by
    intro same
    subst second
    exact headFresh secondMember
  refine ⟨firstMember, secondMember, ?_⟩
  have inequality := before.2.2
  simp only [List.idxOf_cons, cond_eq_ite, beq_iff_eq,
    if_neg headNeFirst, if_neg headNeSecond] at inequality
  exact Nat.add_lt_add_iff_right.mp inequality

end IdBefore

namespace IdAdjacent

/-- The first two identifiers of a duplicate-free list are adjacent. -/
theorem firstTwo
    {first second : EventId}
    {tail : List EventId}
    (noDuplicates : (first :: second :: tail).Nodup) :
    IdAdjacent first second (first :: second :: tail) := by
  have firstNeSecond : first ≠ second := by
    intro same
    subst second
    exact (List.nodup_cons.mp noDuplicates).1 (by simp)
  have firstMember :
      first ∈ first :: second :: tail := by
    simp
  have secondMember :
      second ∈ first :: second :: tail := by
    simp
  refine ⟨?_, ?_⟩
  · refine ⟨firstMember, secondMember, ?_⟩
    simp only [List.idxOf_cons, cond_eq_ite, beq_iff_eq,
      if_neg firstNeSecond]
    exact Nat.zero_lt_succ _
  · intro middle
    rintro ⟨firstBeforeMiddle, middleBeforeSecond⟩
    have positive :
        0 < (first :: second :: tail).idxOf middle := by
      simpa using firstBeforeMiddle.2.2
    have belowOne :
        (first :: second :: tail).idxOf middle < 1 := by
      simpa [List.idxOf_cons, cond_eq_ite, beq_iff_eq,
        firstNeSecond] using middleBeforeSecond.2.2
    have atMostZero :
        (first :: second :: tail).idxOf middle ≤ 0 :=
      Nat.le_of_lt_succ belowOne
    have isZero :
        (first :: second :: tail).idxOf middle = 0 :=
      Nat.eq_zero_of_le_zero atMostZero
    rw [isZero] at positive
    exact (Nat.lt_irrefl 0) positive

/-- Adjacency in a tail is preserved when a fresh head is added. -/
theorem cons
    {first second head : EventId}
    {tail : List EventId}
    (headFresh : head ∉ tail)
    (adjacent : IdAdjacent first second tail) :
    IdAdjacent first second (head :: tail) := by
  constructor
  · exact IdBefore.cons headFresh adjacent.before
  · intro middle
    rintro ⟨firstBeforeMiddle, middleBeforeSecond⟩
    have middleMember :
        middle ∈ head :: tail :=
      firstBeforeMiddle.second_mem
    simp only [List.mem_cons] at middleMember
    rcases middleMember with middleIsHead | middleInTail
    · subst middle
      exact IdBefore.notBeforeHead firstBeforeMiddle
    · have firstInTail := adjacent.before.first_mem
      have secondInTail := adjacent.before.second_mem
      exact adjacent.noBetween
        ⟨IdBefore.tail headFresh firstInTail middleInTail
            firstBeforeMiddle,
          IdBefore.tail headFresh middleInTail secondInTail
            middleBeforeSecond⟩

end IdAdjacent

/--
The reflexive-transitive path generated by adjacent identifiers in one fixed
finite order.
-/
inductive IdAdjacentPath
    (order : List EventId)
    (first : EventId) :
    EventId → Prop where
  | refl
      (member : first ∈ order) :
      IdAdjacentPath order first first
  | step
      {middle last : EventId} :
      IdAdjacentPath order first middle →
      IdAdjacent middle last order →
      IdAdjacentPath order first last

namespace IdAdjacentPath

theorem first_mem
    {order : List EventId}
    {first last : EventId}
    (path : IdAdjacentPath order first last) :
    first ∈ order := by
  induction path with
  | refl member =>
      exact member
  | step previous adjacent inductionHypothesis =>
      exact inductionHypothesis

theorem last_mem
    {order : List EventId}
    {first last : EventId}
    (path : IdAdjacentPath order first last) :
    last ∈ order := by
  cases path with
  | refl member =>
      exact member
  | step previous adjacent =>
      exact adjacent.before.second_mem

/-- Lift every adjacency path through a fresh list head. -/
theorem cons
    {order : List EventId}
    {first last head : EventId}
    (headFresh : head ∉ order)
    (path : IdAdjacentPath order first last) :
    IdAdjacentPath (head :: order) first last := by
  induction path with
  | refl member =>
      exact .refl (by simp [member])
  | step previous adjacent inductionHypothesis =>
      exact .step inductionHypothesis
        (IdAdjacent.cons headFresh adjacent)

/-- Prepend one adjacent edge to an existing path. -/
theorem prepend
    {order : List EventId}
    {first second last : EventId}
    (adjacent : IdAdjacent first second order)
    (path : IdAdjacentPath order second last) :
    IdAdjacentPath order first last := by
  induction path with
  | refl member =>
      exact .step (.refl adjacent.before.first_mem) adjacent
  | step previous nextAdjacent inductionHypothesis =>
      exact .step inductionHypothesis nextAdjacent

/-- The head of a duplicate-free list reaches every member by adjacency. -/
theorem headToMember
    {head last : EventId}
    {tail : List EventId}
    (noDuplicates : (head :: tail).Nodup)
    (lastMember : last ∈ head :: tail) :
    IdAdjacentPath (head :: tail) head last := by
  induction tail generalizing head last with
  | nil =>
      simp only [List.mem_singleton] at lastMember
      subst last
      exact .refl (by simp)
  | cons next rest inductionHypothesis =>
      have headFresh :=
        (List.nodup_cons.mp noDuplicates).1
      have tailNodup :=
        (List.nodup_cons.mp noDuplicates).2
      simp only [List.mem_cons] at lastMember
      rcases lastMember with lastIsHead | lastInTail
      · subst last
        exact .refl (by simp)
      · have tailPath :
            IdAdjacentPath (next :: rest) next last :=
          inductionHypothesis tailNodup
            (List.mem_cons.mpr lastInTail)
        have liftedPath :
            IdAdjacentPath
              (head :: next :: rest) next last :=
          tailPath.cons headFresh
        exact liftedPath.prepend
          (IdAdjacent.firstTwo noDuplicates)

/-- Every strict list order is realized by a path of adjacent identifiers. -/
theorem ofBefore
    {order : List EventId}
    {first last : EventId}
    (noDuplicates : order.Nodup)
    (before : IdBefore first last order) :
    IdAdjacentPath order first last := by
  induction order with
  | nil =>
      simp [IdBefore] at before
  | cons head tail inductionHypothesis =>
      have headFresh :=
        (List.nodup_cons.mp noDuplicates).1
      have tailNodup :=
        (List.nodup_cons.mp noDuplicates).2
      have firstMember := before.first_mem
      have lastMember := before.second_mem
      simp only [List.mem_cons] at firstMember lastMember
      rcases firstMember with firstIsHead | firstInTail
      · subst first
        exact headToMember noDuplicates
          (by simp [lastMember])
      · rcases lastMember with lastIsHead | lastInTail
        · subst last
          exact (IdBefore.notBeforeHead before).elim
        · have tailBefore :
              IdBefore first last tail :=
            IdBefore.tail headFresh
              firstInTail lastInTail before
          exact (inductionHypothesis tailNodup tailBefore).cons
            headFresh

/-- Equality or strict order both produce an adjacency path. -/
theorem ofEqOrBefore
    {order : List EventId}
    {first last : EventId}
    (noDuplicates : order.Nodup)
    (firstMember : first ∈ order)
    (ordered : first = last ∨ IdBefore first last order) :
    IdAdjacentPath order first last := by
  rcases ordered with same | before
  · subst last
    exact .refl firstMember
  · exact ofBefore noDuplicates before

end IdAdjacentPath

namespace Event

/-- In the Treiber event universe, every non-initial write is an RMW. -/
theorem isRMW_of_isWrite_not_initial
    {event : Event α}
    (isWrite : event.IsWrite)
    (notInitial : ¬ event.IsInitial) :
    event.IsRMW := by
  cases event with
  | mk id kind =>
      cases kind with
      | initial =>
          exact (notInitial True.intro).elim
      | algorithm action =>
          cases action <;>
            simp [Event.IsWrite, Event.writtenValue,
              Event.IsRMW] at isWrite ⊢

end Event

namespace AtomicRelationData

/-- Every identifier in the concrete write order names one graph write. -/
theorem exists_write_of_id_mem_writeOrder
    {α : Type}
    {skeleton : EventGraph.Skeleton α}
    (data : AtomicRelationData skeleton)
    {eventId : EventId}
    (idMember : eventId ∈ data.writeOrder) :
    ∃ event,
      event ∈ data.graph.events ∧
        event.id = eventId ∧
        event.IsWrite := by
  change eventId ∈ 0 :: data.writeTail at idMember
  simp only [List.mem_cons] at idMember
  rcases idMember with eventIdZero | inTail
  · subst eventId
    refine ⟨
      (EventGraph.Skeleton.initialEvent : Event α),
      by simp [EventGraph.Skeleton.events],
      rfl, ?_⟩
    exact ⟨none, rfl⟩
  · obtain ⟨event, eventMember, eventIdShape,
        eventWrites, _⟩ :=
      (data.writeTailExact eventId).mp inTail
    exact ⟨event, eventMember, eventIdShape, eventWrites⟩

/-- A write with a strict modification-order predecessor is non-initial. -/
theorem notInitial_of_idBefore
    {α : Type}
    {skeleton : EventGraph.Skeleton α}
    (data : AtomicRelationData skeleton)
    {sourceId : EventId}
    {target : Event α}
    (targetMember : target ∈ data.graph.events)
    (before :
      IdBefore sourceId target.id data.writeOrder) :
    ¬ target.IsInitial := by
  intro targetInitial
  have targetShape :=
    initial_eq_initialEvent targetMember targetInitial
  rw [targetShape] at before
  change
    IdBefore sourceId 0 (0 :: data.writeTail)
      at before
  exact IdBefore.notBeforeHead before

/--
Adjacent write identifiers produce an immediate-modification edge between
their corresponding graph events.
-/
theorem immediateModification_of_idAdjacent
    {α : Type}
    {skeleton : EventGraph.Skeleton α}
    (data : AtomicRelationData skeleton)
    {source target : Event α}
    (sourceMember : source ∈ data.graph.events)
    (targetMember : target ∈ data.graph.events)
    (adjacent :
      IdAdjacent source.id target.id data.writeOrder) :
    data.graph.ImmediateModification source target := by
  refine ⟨sourceMember, targetMember,
    ⟨sourceMember, targetMember, adjacent.before⟩, ?_⟩
  intro middle middleMember middleWrites
  rintro ⟨sourceBeforeMiddle, middleBeforeTarget⟩
  change data.modificationOrder source middle at sourceBeforeMiddle
  change data.modificationOrder middle target at middleBeforeTarget
  exact adjacent.noBetween
    ⟨sourceBeforeMiddle.2.2,
      middleBeforeTarget.2.2⟩

/--
An adjacency path in the concrete write order becomes an RMW release
sequence between the graph events carrying its endpoint identifiers.
-/
theorem releaseSequence_of_idAdjacentPath
    {α : Type}
    {skeleton : EventGraph.Skeleton α}
    (data : AtomicRelationData skeleton)
    {firstId lastId : EventId}
    (path :
      IdAdjacentPath data.writeOrder firstId lastId)
    {head target : Event α}
    (headMember : head ∈ data.graph.events)
    (headId : head.id = firstId)
    (targetMember : target ∈ data.graph.events)
    (targetId : target.id = lastId) :
    data.graph.ReleaseSequence head target := by
  induction path generalizing target with
  | refl member =>
      have sameId : head.id = target.id :=
        headId.trans targetId.symm
      have sameEvent : head = target :=
        skeleton.uniqueIds
          headMember targetMember sameId
      subst target
      exact Graph.ReleaseSequence.head headMember
  | @step middle last previous adjacent inductionHypothesis =>
      obtain ⟨middleEvent, middleMember,
          middleId, middleWrites⟩ :=
        data.exists_write_of_id_mem_writeOrder
          previous.last_mem
      have prefixSequence :
          data.graph.ReleaseSequence head middleEvent :=
        inductionHypothesis
          middleMember middleId
      have eventAdjacency :
          IdAdjacent middleEvent.id target.id data.writeOrder := by
        simpa [middleId, targetId] using adjacent
      have targetWrites : target.IsWrite :=
        data.isWrite_of_id_mem_writeOrder
          targetMember eventAdjacency.before.second_mem
      have targetNotInitial : ¬ target.IsInitial :=
        data.notInitial_of_idBefore
          targetMember eventAdjacency.before
      have targetRMW : target.IsRMW :=
        Event.isRMW_of_isWrite_not_initial
          targetWrites targetNotInitial
      exact Graph.ReleaseSequence.rmw
        prefixSequence
        (data.immediateModification_of_idAdjacent
          middleMember targetMember eventAdjacency)
        targetRMW

/--
Equal or modification-ordered non-initial writes form one release sequence.

The non-initial hypotheses expose the Treiber-specific reason this result is
valid: every strict step after the head is a successful RMW event.
-/
theorem releaseSequence_of_eq_or_modificationOrder
    {α : Type}
    {skeleton : EventGraph.Skeleton α}
    (data : AtomicRelationData skeleton)
    {earlier later : Event α}
    (earlierMember : earlier ∈ data.graph.events)
    (earlierWrites : earlier.IsWrite)
    (_earlierNotInitial : ¬ earlier.IsInitial)
    (laterMember : later ∈ data.graph.events)
    (_laterWrites : later.IsWrite)
    (_laterNotInitial : ¬ later.IsInitial)
    (ordered :
      earlier = later ∨
        data.graph.modificationOrder earlier later) :
    data.graph.ReleaseSequence earlier later := by
  have earlierIdMember :
      earlier.id ∈ data.writeOrder :=
    data.id_mem_writeOrder_of_isWrite
      earlierMember earlierWrites
  have idOrdered :
      earlier.id = later.id ∨
        IdBefore earlier.id later.id data.writeOrder := by
    rcases ordered with same | before
    · exact Or.inl (congrArg Event.id same)
    · change data.modificationOrder earlier later at before
      exact Or.inr before.2.2
  have path :
      IdAdjacentPath
        data.writeOrder earlier.id later.id :=
    IdAdjacentPath.ofEqOrBefore
      data.writeOrderNodup
      earlierIdMember idOrdered
  exact data.releaseSequence_of_idAdjacentPath
    path earlierMember rfl laterMember rfl

/-- Strictly modification-ordered non-initial writes form a release sequence. -/
theorem releaseSequence_of_modificationOrder
    {α : Type}
    {skeleton : EventGraph.Skeleton α}
    (data : AtomicRelationData skeleton)
    {earlier later : Event α}
    (earlierMember : earlier ∈ data.graph.events)
    (earlierWrites : earlier.IsWrite)
    (earlierNotInitial : ¬ earlier.IsInitial)
    (laterMember : later ∈ data.graph.events)
    (laterWrites : later.IsWrite)
    (laterNotInitial : ¬ later.IsInitial)
    (ordered :
      data.graph.modificationOrder earlier later) :
    data.graph.ReleaseSequence earlier later :=
  data.releaseSequence_of_eq_or_modificationOrder
    earlierMember earlierWrites earlierNotInitial
    laterMember laterWrites laterNotInitial
    (Or.inr ordered)

end AtomicRelationData

end WeakMemory.TreiberRC11
